#!/bin/bash
set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
REPO_ROOT=$(cd "$SCRIPT_DIR/.." && pwd)
PACKAGE_DIR="$REPO_ROOT/src-tauri/engine-host/coreml"
BUILD_INFO="$PACKAGE_DIR/Sources/EngineHostCore/BuildInfo.swift"

version=$(sed -n 's/^[[:space:]]*"version":[[:space:]]*"\([^"]*\)".*/\1/p' "$REPO_ROOT/src-tauri/tauri.conf.json" | head -n 1)
if [[ -z "$version" ]]; then
  echo "Could not read version from src-tauri/tauri.conf.json" >&2
  exit 1
fi
git_sha=$(git -C "$REPO_ROOT" rev-parse HEAD)
if [[ ! "$git_sha" =~ ^[0-9a-f]{40}$ ]]; then
  echo "git rev-parse HEAD did not return a full SHA" >&2
  exit 1
fi

dirty=false
if git -C "$REPO_ROOT" status --porcelain=v1 --untracked-files=all \
    | sed '/src-tauri\/engine-host\/coreml\/Sources\/EngineHostCore\/BuildInfo\.swift/d' \
    | grep -q .; then
  dirty=true
fi

mkdir -p "$(dirname "$BUILD_INFO")"
printf '%s\n' \
  "// Generated by scripts/build-engine-host.sh; do not edit." \
  "import Foundation" \
  "" \
  "public enum BuildInfo {" \
  "    public static let version = \"$version\"" \
  "    public static let gitSHA = \"$git_sha\"" \
  "    public static let dirty = $dirty" \
  "}" > "$BUILD_INFO"

cd "$PACKAGE_DIR"
mkdir -p .build/swiftpm-cache .build/swiftpm-config .build/swiftpm-security .build/clang-module-cache .build/swift-module-cache
export CLANG_MODULE_CACHE_PATH="$PACKAGE_DIR/.build/clang-module-cache"
export SWIFT_MODULECACHE_PATH="$PACKAGE_DIR/.build/swift-module-cache"
swift build -c release \
  -debug-info-format none \
  --cache-path .build/swiftpm-cache \
  --config-path .build/swiftpm-config \
  --security-path .build/swiftpm-security \
  --scratch-path .build \
  --disable-sandbox
bin_path=$(swift build -c release --show-bin-path \
  -debug-info-format none \
  --cache-path .build/swiftpm-cache \
  --config-path .build/swiftpm-config \
  --security-path .build/swiftpm-security \
  --scratch-path .build \
  --disable-sandbox)
echo "$bin_path/sagascript-engine-host"
