use std::process::Command;

fn git(args: &[&str]) -> Option<String> {
    Command::new("git")
        .args(args)
        .output()
        .ok()
        .filter(|o| o.status.success())
        .and_then(|o| String::from_utf8(o.stdout).ok())
        .map(|s| s.trim_end().to_string())
}

/// Generated by Tauri build scripts earlier in the same CI job; the workflow's
/// `scripts/ci-build-identity.mjs` allows exactly these paths in an otherwise clean tree, so they
/// must not mark the host as dirty. Keep in sync with `ALLOWED_GENERATED_PATHS` there.
const ALLOWED_GENERATED: [&str; 4] = [
    "src-tauri/gen/schemas/acl-manifests.json",
    "src-tauri/gen/schemas/capabilities.json",
    "src-tauri/gen/schemas/desktop-schema.json",
    "src-tauri/gen/schemas/windows-schema.json",
];

/// True when `git status --porcelain=v1` lists anything besides the allowed generated files.
/// (Porcelain paths are relative to the repository root regardless of the working directory.)
fn is_dirty(porcelain: &str) -> bool {
    porcelain
        .lines()
        .filter(|line| !line.is_empty())
        .any(|line| !ALLOWED_GENERATED.contains(&line.get(3..).unwrap_or(line).trim_matches('"')))
}

fn main() {
    println!("cargo:rerun-if-env-changed=SAGASCRIPT_GIT_SHA");
    if let Some(git_dir) = git(&["rev-parse", "--absolute-git-dir"]) {
        println!("cargo:rerun-if-changed={git_dir}/HEAD");
        println!("cargo:rerun-if-changed={git_dir}/index");
    }
    let sha = std::env::var("SAGASCRIPT_GIT_SHA")
        .ok()
        .or_else(|| git(&["rev-parse", "HEAD"]))
        .filter(|s| s.len() == 40 && s.bytes().all(|b| b.is_ascii_hexdigit()))
        .unwrap_or_else(|| "0".repeat(40));
    let dirty = git(&["status", "--porcelain=v1", "--untracked-files=all"])
        .is_some_and(|status| is_dirty(&status));
    println!("cargo:rustc-env=SAGASCRIPT_HOST_GIT_SHA={sha}");
    println!("cargo:rustc-env=SAGASCRIPT_HOST_DIRTY={dirty}");
}

#[cfg(test)]
mod tests {
    use super::is_dirty;

    #[test]
    fn only_allowed_generated_files_are_ignored() {
        assert!(!is_dirty(""));
        assert!(!is_dirty(" M src-tauri/gen/schemas/windows-schema.json\n?? src-tauri/gen/schemas/acl-manifests.json"));
        assert!(is_dirty(" M src-tauri/gen/schemas/windows-schema.json\n M src-tauri/src/lib.rs"));
        assert!(is_dirty("?? scripts/__pycache__/x.pyc"));
    }
}
